### ISSUE TITLE
DaCe GPU backend either crashes or gives compilation errors for hdiff benchmark

### ISSUE THREAD

**Issue by shriram-jagan** [spcl/npbench#21]
Hi, I'm trying to run the "hdiff" benchmark for different backends, but I run into a segfault if I set DACE_CONFIG. The cuda arch is set to "86" for A6000 GPU based on the information given [here](https://developer.nvidia.com/cuda-gpus).

dace.conf file:
```
compiler:
  cpu:
   executable: 'nvc++'
   args: -std=c++14 -fPIC -O3
  cuda:
    cuda_arch: '86' 
    default_block_size: 32, 4, 4
  use_cache: true
```

If I unset DACE_CONFIG, I get the attached error [t.txt](https://github.com/spcl/npbench/files/12526425/t.txt). My `cudatoolkit` version is 11.7.1 and `cuda-version` is 11.7

The DaCe CPU version works fine for me. 

Could someone tell me what's missing in my setup/environment?
